# Generated by Django 4.1.1 on 2022-10-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='applylink',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='text',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='title',
        ),
    ]
