# Generated by Django 4.1.1 on 2022-10-03 09:11

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobs_applylink_remove_jobs_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_expires_at',
            field=models.DateField(default=jobs.models.in_three_days),
        ),
    ]
