# Generated by Django 4.1.1 on 2022-10-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_company_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_login',
        ),
    ]
