# Generated by Django 4.1.1 on 2022-10-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_company_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_login',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
